server:
  port: 9000
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
zuul:
  ignored-services: '*'
  routes:
    employee: # 自定义路由规则的名称，在底层的数据结构中是 Map 的键
      serviceId: feign-consumer7000 # 目标微服务名称，ZuulRoute 类型的一个属性
      path: /zuul-emp/** # 用来代替目标微服务名称的路径，uulRoute 类型的一个属性
# /**表示匹配多层路径，如果没有加/**则不能匹配后续的多层路径了