server:
  port: 80
spring:
  application:
    name: zuul-80
  redis:
    host: 39.104.117.161
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*" # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头）
  routes:
    crowd-portal:
      service-id: authentication-consumer-4000
      path: /**
    crowd-project:
      service-id: project-consumer-5000
      path: /project/**
    crowd-order:
      service-id: order-crowd-7000
      path: /order/**
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000