server:
  port: 6000
spring:
  application:
    name: order-crowd-6000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 39.104.117.161
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka