server:
  port: 4000
#  servlet:
#    context-path: /aa
spring:
  #  http:
  #    encoding:
  #      force: true
  #      charset: utf-8
  #      enabled: true
  application:
    name: authentication-consumer-4000
  redis:
    host: 39.104.117.161
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    app-code:
    host:
    method: GET
    path: /codeNotice
    sign:
    skin:
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000